In [7]:
import pandas as pd

In [8]:
df = pd.read_parquet('CLEANED_SWIM_DATA.parquet')

In [9]:
df.head()

,Event,Conf_Rank,Time,Name,School,Standard,Date,Gender,Division,Season,SeasonYear,Time_Adj,Time_Sec,Div_Rank,NCAA_Rank,ID,Power_Tot,Power,Record,Points
0,50 Freestyle SCY Male,-1,21.22,Ben Beldner,Binghamton,NA,2000-01-01,M,HS,00_01,2001,0 days 00:00:21.220000,21.22,-1,-1,394588,22.71,20.52,17.63,573.483330
1,50 Freestyle SCY Male,-1,20.87,Justin Meyn,Binghamton,NA,2000-01-01,M,HS,00_01,2001,0 days 00:00:20.870000,20.87,-1,-1,471360,10.06,20.80,17.63,602.822689
2,50 Freestyle SCY Male,-1,21.31,Joshua Franco,New Jersey Institute of Technology,NA,2000-01-01,M,HS,00_01,2001,0 days 00:00:21.310000,21.31,-1,-1,395308,12.40,22.05,17.63,566.247878
3,50 Freestyle SCY Male,-1,21.05,Gabe Laracuente,UMBC,NA,2000-01-01,M,HS,00_01,2001,0 days 00:00:21.050000,21.05,-1,-1,404642,13.77,23.93,17.63,587.490213
4,50 Freestyle SCY Male,-1,21.70,Ryan Board,Binghamton,NA,2000-01-01,M,HS,00_01,2001,0 days 00:00:21.700000,21.70,-1,-1,422211,18.21,28.82,17.63,536.262879

In [10]:
df.dtypes

Event                category
Conf_Rank               int64
Time           string[python]
Name           string[python]
School         string[python]
Standard             category
Date           datetime64[ns]
Gender               category
Division             category
Season               category
SeasonYear              int64
Time_Adj      timedelta64[ns]
Time_Sec              float64
Div_Rank                int64
NCAA_Rank               int64
ID                      int64
Power_Tot             float64
Power                 float64
Record                float64
Points                float64
dtype: object

In [16]:
df.loc[:,'isHS'] = df.loc[:,'Division'] == 'HS'

In [17]:
df[df.Name=='Vineet Ranade']

,Event,Conf_Rank,Time,Name,School,Standard,Date,Gender,Division,Season,...,Time_Adj,Time_Sec,Div_Rank,NCAA_Rank,ID,Power_Tot,Power,Record,Points,isHS
2787,50 Freestyle SCY Male,-1,21.81,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:00:21.810000,21.81,-1,-1,418728,21.88,33.78,17.63,528.189715,True
13941,100 Freestyle SCY Male,-1,46.86,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:00:46.860000,46.86,-1,-1,418728,21.88,23.82,39.90,617.322113,True
24872,200 Freestyle SCY Male,-1,1:41.96,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:01:41.960000,101.96,-1,-1,418728,21.88,19.71,88.81,660.839707,True
34949,500 Freestyle SCY Male,-1,4:37.66,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:04:37.660000,277.66,-1,-1,418728,21.88,22.23,242.31,664.620993,True
42965,1000 Freestyle SCY Male,-1,9:59.66,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:09:59.660000,599.66,-1,-1,418728,21.88,36.06,513.93,629.501353,True
48146,1650 Freestyle SCY Male,-1,16:50.68,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:16:50.680000,1010.68,-1,-1,418728,21.88,37.04,852.08,599.239041,True
54083,100 Backstroke SCY Male,-1,53.46,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:00:53.460000,53.46,-1,-1,418728,21.88,45.20,43.35,533.188093,True
63578,200 Backstroke SCY Male,-1,1:58.60,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:01:58.600000,118.60,-1,-1,418728,21.88,49.75,95.37,519.973584,True
72349,100 Breaststroke SCY Male,-1,58.91,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:00:58.910000,58.91,-1,-1,418728,21.88,30.56,48.71,565.310849,True
80881,200 Breaststroke SCY Male,-1,2:06.62,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:02:06.620000,126.62,-1,-1,418728,21.88,26.64,106.35,592.523467,True
88884,100 Butterfly SCY Male,-1,50.59,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:00:50.590000,50.59,-1,-1,418728,21.88,25.59,42.80,605.532237,True
98076,200 Butterfly SCY Male,-1,1:52.90,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:01:52.900000,112.90,-1,-1,418728,21.88,25.59,97.35,641.100391,True
104761,100 Individual Medley SCY Male,-1,1:04.14,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:01:04.140000,64.14,-1,-1,418728,21.88,100.00,46.63,384.246022,True
111840,200 Individual Medley SCY Male,-1,1:54.71,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:01:54.710000,114.71,-1,-1,418728,21.88,26.19,96.34,592.401414,True
121093,400 Individual Medley SCY Male,-1,4:07.82,Vineet Ranade,Rose-Hulman Institute of Technology,NA,2000-01-01,M,HS,00_01,...,0 days 00:04:07.820000,247.82,-1,-1,418728,21.88,26.67,208.82,598.283763,True
195995,50 Freestyle SCY Male,13,21.82,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2021-12-03,M,III,21_22,...,0 days 00:00:21.820000,21.82,553,2319,418728,21.88,-1.00,17.63,527.463847,False
196018,100 Freestyle SCY Male,4,46.26,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2022-02-12,M,III,21_22,...,0 days 00:00:46.260000,46.26,187,1288,418728,21.88,-1.00,39.90,641.655324,False
196049,200 Freestyle SCY Male,1,1:40.79,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2022-02-11,M,III,21_22,...,0 days 00:01:40.790000,100.79,107,965,418728,21.88,-1.00,88.81,684.121556,False
196092,500 Freestyle SCY Male,23,5:10.80,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2022-01-22,M,III,21_22,...,0 days 00:05:10.800000,310.80,931,2473,418728,21.88,-1.00,242.31,473.882840,False
196172,100 Breaststroke SCY Male,3,57.79,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2022-02-11,M,III,21_22,...,0 days 00:00:57.790000,57.79,196,940,418728,21.88,-1.00,48.71,598.820012,False
196190,200 Breaststroke SCY Male,2,2:04.89,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2022-02-12,M,III,21_22,...,0 days 00:02:04.890000,124.89,111,661,418728,21.88,-1.00,106.35,617.489370,False
196214,100 Butterfly SCY Male,13,53.77,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2021-11-06,M,III,21_22,...,0 days 00:00:53.770000,53.77,660,2438,418728,21.88,-1.00,42.80,504.325813,False
196232,200 Butterfly SCY Male,6,2:00.13,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2022-01-15,M,III,21_22,...,0 days 00:02:00.130000,120.13,391,1447,418728,21.88,-1.00,97.35,532.173735,False
196249,200 Individual Medley SCY Male,1,1:51.82,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2022-02-10,M,III,21_22,...,0 days 00:01:51.820000,111.82,87,749,418728,21.88,-1.00,96.34,639.530796,False
196277,400 Individual Medley SCY Male,10,4:23.13,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2021-11-06,M,III,21_22,...,0 days 00:04:23.130000,263.13,413,1386,418728,21.88,-1.00,208.82,499.810272,False
217900,50 Freestyle SCY Male,1,21.12,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2022-12-01,M,III,22_23,...,0 days 00:00:21.120000,21.12,207,1375,418728,21.88,-1.00,17.63,581.668031,False
217919,100 Freestyle SCY Male,1,45.93,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-02-11,M,III,22_23,...,0 days 00:00:45.930000,45.93,137,1135,418728,21.88,-1.00,39.90,655.585517,False
217943,200 Freestyle SCY Male,1,1:39.98,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-02-08,M,III,22_23,...,0 days 00:01:39.980000,99.98,56,807,418728,21.88,-1.00,88.81,700.884108,False
218030,100 Breaststroke SCY Male,2,57.63,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-02-10,M,III,22_23,...,0 days 00:00:57.630000,57.63,195,963,418728,21.88,-1.00,48.71,603.821441,False
218038,200 Breaststroke SCY Male,2,2:04.55,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-02-11,M,III,22_23,...,0 days 00:02:04.550000,124.55,100,687,418728,21.88,-1.00,106.35,622.560106,False
218046,100 Butterfly SCY Male,2,49.96,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2022-12-02,M,III,22_23,...,0 days 00:00:49.960000,49.96,131,984,418728,21.88,-1.00,42.80,628.729761,False
218073,100 Individual Medley SCY Male,3,55.54,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2022-10-15,M,III,22_23,...,0 days 00:00:55.540000,55.54,162,588,418728,21.88,-1.00,46.63,591.804986,False
218078,200 Individual Medley SCY Male,1,1:50.38,Vineet Ranade,Rose-Hulman Institute of Technology,B,2022-12-01,M,III,22_23,...,0 days 00:01:50.380000,110.38,36,611,418728,21.88,-1.00,96.34,664.888401,False
225952,50 Freestyle SCY Male,4,21.72,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-11-30,M,III,23_24,...,0 days 00:00:21.720000,21.72,573,2309,418728,21.88,-1.00,17.63,534.782853,False
225970,100 Freestyle SCY Male,1,44.85,Vineet Ranade,Rose-Hulman Institute of Technology,B,2024-02-17,M,III,23_24,...,0 days 00:00:44.850000,44.85,36,655,418728,21.88,-1.00,39.90,704.095137,False
225984,200 Freestyle SCY Male,1,1:37.63,Vineet Ranade,Rose-Hulman Institute of Technology,B,2024-02-24,M,III,23_24,...,0 days 00:01:37.630000,97.63,13,397,418728,21.88,-1.00,88.81,752.723963,False
226007,500 Freestyle SCY Male,17,5:10.00,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-10-21,M,III,23_24,...,0 days 00:05:10,310.00,984,2545,418728,21.88,-1.00,242.31,477.561086,False
226033,50 Backstroke SCY Male,10,25.81,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2024-01-13,M,III,23_24,...,0 days 00:00:25.810000,25.81,545,1544,418728,21.88,-1.00,20.07,470.195105,False
226047,100 Backstroke SCY Male,15,55.30,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-11-17,M,III,23_24,...,0 days 00:00:55.300000,55.30,653,2054,418728,21.88,-1.00,43.35,481.716932,False
226061,100 Breaststroke SCY Male,1,56.27,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2024-02-24,M,III,23_24,...,0 days 00:00:56.270000,56.27,110,713,418728,21.88,-1.00,48.71,648.669747,False
226069,200 Breaststroke SCY Male,1,2:00.65,Vineet Ranade,Rose-Hulman Institute of Technology,B,2024-02-17,M,III,23_24,...,0 days 00:02:00.650000,120.65,34,401,418728,21.88,-1.00,106.35,684.905264,False
226076,50 Butterfly SCY Male,1,23.19,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-10-05,M,III,23_24,...,0 days 00:00:23.190000,23.19,50,213,418728,21.88,-1.00,19.90,631.912554,False
226084,100 Butterfly SCY Male,4,51.39,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-10-05,M,III,23_24,...,0 days 00:00:51.390000,51.39,338,1614,418728,21.88,-1.00,42.80,577.690804,False
226100,200 Butterfly SCY Male,7,1:59.25,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-11-04,M,III,23_24,...,0 days 00:01:59.250000,119.25,392,1465,418728,21.88,-1.00,97.35,544.042346,False
226105,100 Individual Medley SCY Male,1,52.72,Vineet Ranade,Rose-Hulman Institute of Technology,NS,2023-10-05,M,III,23_24,...,0 days 00:00:52.720000,52.72,35,220,418728,21.88,-1.00,46.63,691.942556,False
226110,200 Individual Medley SCY Male,1,1:49.24,Vineet Ranade,Rose-Hulman Institute of Technology,B,2024-02-15,M,III,23_24,...,0 days 00:01:49.240000,109.24,22,492,418728,21.88,-1.00,96.34,685.922188,False

In [18]:
pivot_table = df.pivot_table(values='Points', index='ID', columns='isHS', aggfunc='mean')

# Add a new column for the difference between False and True averages
pivot_table['Difference'] = abs(pivot_table[False] - pivot_table[True])

# Display the pivot table with the new 'Difference' column
pivot_table

isHS          False        True  Difference
ID
2870     489.829804  445.036733   44.793071
3480     440.299992  561.707158  121.407166
7361     461.058307  632.627089  171.568782
19185    615.205323  805.624563  190.419240
31849    433.350845  566.791539  133.440695
...             ...         ...         ...
2968147  409.771922  207.230391  202.541532
3008853  436.281318  229.529546  206.751772
3017695  527.600540  172.140176  355.460364
3036513  349.143568  150.443217  198.700351
3040113  618.038019  229.142408  388.895610

[11338 rows x 3 columns]

In [19]:
pivot_table.loc[418728]

isHS
False         601.786337
True          582.151516
Difference     19.634821
Name: 418728, dtype: float64